#!/bin/bash
# 1st argument: absolute or relative path to the base directory
# Defaults to dirname `git rev-parse --absolute-git-dir` if not specified

pushd `dirname $0`
source docker-ssh-setup
source script-helpers

testdir=$1
if [ $# -lt 1 ]; then
	testdir=$(dirname $(git rev-parse --absolute-git-dir))
	echo "Directory not specified, using ${testdir}"
	githubstudent=aesd-classroom-default
else
	if [ $# -lt 2 ]; then
		# set the student based on the prefix before the first _ in the test directory basename
		githubstudent=$(basename ${testdir} | sed -n 's/\(.\?\)_.*/\1/p')
	else
		githubstudent=$2
	fi
fi
export githubstudent
echo "Testing submission from student ${githubstudent}"

. ./assignment-test.sh ${testdir}

rc=$?
if [ $rc -ne 0 ]; then
	add_validate_error "Failed to run assignment test script"
fi

if [ ! "${validate_error}" == "" ]; then
	printf "${RED}Validation script failed with ${validate_error}${NC}\n"
	printf "${RED}Exiting with failure${NC}\n"
else
	echo "No validation failures, script completed successfully"
fi

