#!/bin/sh
# 1st argument: absolute or relative path to the directory containing code to be tested
cd `dirname $0`

testdir=$1
set -e
# set the student based on the prefix before the first _ in the test directory basename
githubstudent=$(basename ${testdir} | sed -n 's/\(.\?\)_.*/\1/p')
docker build -t aesd-test:latest .
docker run -t -i -v ${testdir}:/test-source aesd-test:latest ./assignment-testing/do-test-local-timeout /test-source ${githubstudent}