#!/bin/bash
# 1st argument: absolute or relative path to the base directory
# Defaults to dirname `git rev-parse --absolute-git-dir` if not specified

pushd `dirname $0`

source script-helpers
source assignment-timeout

testdir=$1
githubstudent=$2
timeout ${assignment_timeout} ./do-test-local ${testdir} ${githubstudent}
