#!/bin/sh
# 1st argument: absolute or relative path to the base directory
# Defaults to dirname `git rev-parse --absolute-git-dir` if not specified

cd `dirname $0`

. ./script-helpers
testdir=$1
mkdir -p ../../build
if [ $# -lt 1 ]; then
	testdir=$(dirname $(git rev-parse --show-toplevel)/build)
	echo "Directory not specified, using ${testdir}"
else
	if [ $# -lt 2 ]; then
		# set the student based on the prefix before the first _ in the test directory basename
		githubstudent=$(basename ${testdir} | sed -n 's/\(.\?\)_.*/\1/p')
	else
		githubstudent=$2
	fi
fi
export githubstudent
echo "Testing submission from student ${githubstudent}"

realpath ${testdir}
./test.sh
cd ..

. ./assignment-test.sh ${testdir}

if [ $? -ne 0 ]; then
	add_validate_error "Failed to run assignment test script"
fi

if [ ! "${validate_error}" == "" ]; then
	echo "Validation script failed with ${validate_error}"
	echo "Exiting with failure"
	exit 1
fi
echo "No validation failures, script completed successfully"
exit 0