#!/bin/sh
# 1st argument: absolute or relative path to the base directory
# Defaults to dirname `git rev-parse --absolute-git-dir` if not specified

cd `dirname $0`

. script-helpers
. assignment-timeout

testdir=$1
githubstudent=$2
timeout ${assignment_timeout} ./do-test-local ${testdir} ${githubstudent}
