#!/bin/sh
# 1st argument: absolute or relative path to the base directory
# Defaults to dirname `git rev-parse --absolute-git-dir` if not specified

cd `dirname $0`

testdir=$1
if [ $# -lt 1 ]; then
	testdir=$(dirname $(git rev-parse --absolute-git-dir))
	echo "Directory not specified, using ${testdir}"
fi

./do-docker-test ${testdir}